name: lg_face
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4
  ssh2: ^2.2.3
  json_theme: ^4.0.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 30

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf
